# Generated by Django 5.1.6 on 2025-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_description',
            field=models.TextField(default='Default description', max_length=450),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.CharField(max_length=25),
        ),
    ]
